### ISSUE TITLE
"Reported from in-game: Can't add blocks to veinminer whitelist" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [NanobotZ/tml_VeinMiner_mod#19]
tModLoader version: 0.11.5
 
| Mods:  | - | - |
| :--- | :--- | :--- |
| `Just another Alchemist NPC 2.4` | `Boss Checklist 0.2.1` | `Calamity Mod (No Calamity Music) 1.4.2.107` |
| `Census - Town NPC Checklist 0.3.1` | `Cheat Sheet 0.6.1` | `Calamity Mod Extra Music 1.0.7.5` |
| `Yet Another Boss Health Bar 1.3.2` | `Mod Helpers 5.3.3` | `Magic Storage 0.4.3.5` |
| `MaxStackPlusPlus 1.0` | `MoreAccesories+ 2.3` | `Pug Mount 0.1` |
| `Recipe Browser 0.8.4` | `Rewards 2.2.4.3` | `SuperQuickRespawn 1.0.1` |
| `VeinMiner 1.3.1` | - | - |
 
| Name | Male | Has Demon Heart | Difficulty mode | Life | Mana | Defense |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| pug boi | True | False | 0 | 100 of 100 | 80 of 80 | 4 |
 
**Player pug boi's (0) equipment:**
 
| Accessory 1 | Accessory 2 | Vanity 1 | Vanity 2 | Vanity 3 | Vanity 4 |
| :--- | :--- | :--- | :--- | :--- | :--- |
| Hard Radar | Guarding Shackle | Familiar Wig | Red's Breastplate | Red's Leggings | Red's Wings |
 
Is day: True, Time of day/night: 22417, Elapsed half days: 3
 
World name: BIG BOYE MOD, world size: Medium
 
World progress: none
 
Items on ground: 43, Npcs active: 12
 
Player count: 1 (multiplayer)
 
Autopause: False
 
Autosave: True
 
Lighting mode: 1
 
Lighting threads: 0
 
Frame skip mode: 1
 
Is screen maximized: True
 
Screen resolution: 1440 837
 
Quality style: 3
 
Background on: False
 
Child safety: True
 
Game zoom: 1
 
UI zoom: 1
 
FrameworkVersion.Framework: NetFramework
 
FrameworkVersion.Version: 4.7.2
 
 
 
Recent error logs:
```
...
at CheatSheet.AllItemsMenu.DrawUpdateAll(SpriteBatch spriteBatch) in CheatSheet\AllItemsMenu.cs:line 62
at CheatSheet.CheatSheet.<ModifyInterfaceLayers>b__47_1() in CheatSheet.cs:line 396
at Terraria.UI.LegacyGameInterfaceLayer.DrawSelf()
at Terraria.UI.GameInterfaceLayer.Draw()
at Terraria.Main.DrawInterface(GameTime gameTime)
at Terraria.Main.DoDraw(GameTime gameTime)
at Terraria.Main.Draw(GameTime gameTime)
at Microsoft.Xna.Framework.Game.DrawFrame()
at Microsoft.Xna.Framework.Game.Tick()
at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
at Microsoft.Xna.Framework.GameHost.OnIdle()
at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
at System.Windows.Forms.Application.Run(Form mainForm)
at Microsoft.Xna.Framework.WindowsGameHost.Run()
at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
at Terraria.Program.LaunchGame_()
at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
at Terraria.WindowsLaunch.Main(String[] args)

[21:47:05] [31/INFO] [StatusText]: Receiving tile data
```
 
When I click the button to add blocks to whitelist, it doesnt do anything making it so I cant mine lead with veinminer.

**Comment by NanobotZ** [comment]
did you have Smart Cursor on? if you did, it point to the tile selected by smart cursor.
otherwise impossible
