### ISSUE TITLE
"Reported from in-game: No tile additions?" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [NanobotZ/tml_VeinMiner_mod#24]
tModLoader version: 0.11.6.2
 
| Mods:  | - | - |
| :--- | :--- | :--- |
| `Boss Checklist 1.0.15` | `Calamity Mod (No Calamity Music) 1.4.4.1` | `Calamity Mod Music 1.4.4.1` |
| `Yet Another Boss Health Bar 1.3.2` | `Mod Helpers 5.5.2` | `Magic Storage 0.4.3.5` |
| `No More Tombs 1.0.1` | `Recipe Browser 0.8.5.1` | `Rewards 2.2.4.3` |
| `Shorter Respawn Time 1.0` | `Thorium Mod 1.6.2.1` | `VeinMiner 1.3.1` |
 
| Name | Male | Has Demon Heart | Difficulty mode | Life | Mana | Defense |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Roderick | False | False | 0 | 100 of 100 | 20 of 20 | 0 || Rutger | True | False | 0 | 100 of 100 | 60 of 60 | 0 |
 
**Player Roderick's (0) equipment:**
 
| - |
| :--- |
| - |
 
**Player Rutger's (1) equipment:**
 
| Accessory 1 |
| :--- |
| Brisk Hermes Boots |
 
Is day: False, Time of day/night: 3720, Elapsed half days: 3
 
World name: Suburban, world size: Small
 
World progress: none
 
Items on ground: 26, Npcs active: 8
 
Player count: 2 (multiplayer)
 
Autopause: False
 
Autosave: True
 
Lighting mode: 0
 
Lighting threads: 7
 
Frame skip mode: 1
 
Is screen maximized: False
 
Screen resolution: 1920 1080
 
Quality style: 1
 
Background on: True
 
Child safety: False
 
Game zoom: 1
 
UI zoom: 1
 
FrameworkVersion.Framework: NetFramework
 
FrameworkVersion.Version: 4.8
 
 
 
Recent error logs:
```
...
at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
at Microsoft.Xna.Framework.GameHost.OnIdle()
at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
at System.Windows.Forms.Application.Run(Form mainForm)
at Microsoft.Xna.Framework.WindowsGameHost.Run()
at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
at Terraria.Program.LaunchGame_()
at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
at Terraria.WindowsLaunch.Main(String[] args)

```
 
I cant add tiles to the vein miner

**Comment by NanobotZ** [comment]
did you have Smart Cursor on? if you did, it point to the tile selected by smart cursor.
otherwise impossible
